services:
  mysql:
    image: mysql:8.4
    container_name: erp-mysql
    command: >
      mysqld
      --default-time-zone=+08:00
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    environment:
      MYSQL_DATABASE: erp
      MYSQL_USER: erpuser
      MYSQL_PASSWORD: erppass
      MYSQL_ROOT_PASSWORD: rootpass
      TZ: Asia/Taipei
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # 若有初始化 SQL 檔可掛在這邊：
      # - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uerpuser", "-perppass"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2
    container_name: erp-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp-app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      TZ: Asia/Taipei
      SERVER_PORT: 8443
      DATASOURCE_URL: jdbc:mysql://mysql:3306/erp?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true
      DATASOURCE_USERNAME: erpuser
      DATASOURCE_PASSWORD: erppass
      DB_POOL_SIZE: 15
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: super-secret-change-me
      # TURNSTILE_SECRET: xxx（若你用到）
    ports:
      - "8080:8080"   # HTTP
      - "8443:8443"   # 若你有啟用 SSL
    # 若使用 Spring Boot 3 layer jar，可加快重建速度（非必須）：
    # volumes:
    #   - ~/.m2:/home/spring/.m2
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
